### ISSUE TITLE
Add the Data Annotations header as standard

### ISSUE THREAD

**Issue by paulhasell** [AshV/AshV.WebApiTester.XTB#5]
Hi, would you consider adding the following Header as standard:

Prefer   odata.include-annotations="OData.Community.Display.V1.FormattedValue"

This gets all the optionset, currency, date etc as formatted strings, ideal for reporting and UX work

**Comment by AshV** [comment]
Added changes to the code https://github.com/AshV/AshV.WebApiTester.XTB/commit/90eef92addc76e0d9a4d360f2eb694f4f17b6f7d , will be published soon along with upcoming release.
